### ISSUE TITLE
Fetch Additional Course Section Information

### ISSUE THREAD

**Issue by rdick** [limseung1/coursescheduler#25]
This will need to be done later potentially.

When someone clicks the accordion down button it will fetch / scrap additional course information. This still needs to be discussed further

![image](https://user-images.githubusercontent.com/62073529/201496793-b64a54e2-89b3-497f-99aa-56681cffc80f.png)

**Comment by limseung1** [comment]
I think this is very good idea. I think clicking, and opening the accordion is good indicator that user wants to see more detail.
