### ISSUE TITLE
Download a Headless Scrapper + Remove react-bootstrap

### ISSUE THREAD

**Issue by rdick** [limseung1/coursescheduler#36]
Need a headless scrapper to scrap from rate my professor. 

Remove react-bootstrap to get extra space

**Comment by limseung1** [comment]
Cheerios already support headless scrapping, though page navigation is not allowed.

I agree with removing react-bootstrap, as long as it doesn't trigger regression - as it's highly likely we may have to find out which components are using react-bootstrap.
